name: TNTRun
main: TNTRun\Main
version: 1.1.0
api: 3.7.0
author: BeckenPlayZMCPE
commands:
    tr:
        usage: /tr <sub-command>
        description: All Commands
        permission: TNTRun.command
